article/urls.py
from django.contrib import admin
from django.urls import path
from article.views import dashboard, add_article, ind_article, ind_article_edit, ind_article_delete, articles

app_name = "article"

urlpatterns = [
    path("", articles, name="articles"),
    path('dashboard/', dashboard, name="dashboard"),
    path('dashboard/<int:id>', ind_article, name="ind_article"),
    path('dashboard/edit/<int:id>', ind_article_edit, name="ind_article"),
    path('dashboard/delete/<int:id>', ind_article_delete, name="ind_article"),
    path('add-article/', add_article, name="article_add"),

    path('mainpage', add_article, name="main_page_article"),
    path('new/api', dashboard),
]

firstProject/urls.py
from django.contrib import admin
from django.urls import path, include
from article import views as views_article
from user import views as views_user
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views_article.index, name="index"),
    path('about/', views_article.about, name="about"),
    path('detail/<int:id>', views_article.detail, name="detail"),
    path('article/', include("article.urls")),
    path('user/', include("user.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path
from user import views

app_name = "user"

urlpatterns = [
    path('register/', views.register, name="register"),
    path('login/', views.loginUser, name="login"),
    path('logout/', views.logOut, name="logout"),
]

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'index' %}" exact> &#169;CBlog</a>
  <button
    class="navbar-toggler"
    type="button"
    data-toggle="collapse"
    data-target="#navbarNav"
    aria-controls="navbarNav"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'about'%}">About</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'article:articles'%}">Articles</a>
      </li>

      <form class="form-inline my-2 my-lg-0">
        {% csrf_token %}
        <input
          class="form-control mr-sm-2"
          type="search"
          placeholder="Search"
          aria-label="Search"
          name="keyword"
        />
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">
          Search
        </button>
      </form>
    </ul>

    {% if request.user.is_authenticated %}
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'article:dashboard'%}">Dashboard</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'user:register'%}" exact>Register</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'user:logout'%}" exact>Logout</a>
      </li>
    </ul>

    {% else %}
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'user:register'%}" exact>Register</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'user:login'%}" exact>Login</a>
      </li>
    </ul>
    {% endif %}
  </div>
</nav>