article/urls.py
from django.contrib import admin
from django.urls import path
from article.views import dashboard, add_article, ind_article, ind_article_edit, ind_article_delete, articles

app_name = "article"

urlpatterns = [
    path("", articles, name="articles"),
    path('dashboard/', dashboard, name="dashboard"),
    path('dashboard/<int:id>', ind_article, name="ind_article"),
    path('dashboard/edit/<int:id>', ind_article_edit, name="ind_article"),
    path('dashboard/delete/<int:id>', ind_article_delete, name="ind_article"),
    path('add-article/', add_article, name="article_add"),

    path('mainpage', add_article, name="main_page_article"),
    path('new/api', dashboard),
]

firstProject/urls.py
from django.contrib import admin
from django.urls import path, include
from article import views as views_article
from user import views as views_user
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views_article.index, name="index"),
    path('about/', views_article.about, name="about"),
    path('detail/<int:id>', views_article.detail, name="detail"),
    path('article/', include("article.urls")),
    path('user/', include("user.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path
from user import views

app_name = "user"

urlpatterns = [
    path('register/', views.register, name="register"),
    path('login/', views.loginUser, name="login"),
    path('logout/', views.logOut, name="logout"),
]

article/models.py
from django.db import models
from ckeditor.fields import RichTextField
# Create your models here.


class Article(models.Model):
    author = models.ForeignKey("auth.User", on_delete=models.CASCADE,
                               verbose_name="Name of the author")
    title = models.CharField(max_length=50,
                             verbose_name="title is related with ")
    # content = models.TextField()
    content = RichTextField()
    article_image = models.FileField(
        blank=True, null=True, verbose_name="Add picture to Article")
    created_date = models.DateTimeField(
        auto_now_add=True, null=True, verbose_name="Add picture to article")

    def __str__(self):
        return self.title

article/forms.py
from django import forms
from article.models import Article


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title", "content", "article_image"]

article/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404
from django.contrib import messages
from article.forms import ArticleForm
from article.models import Article
from django.contrib.auth.decorators import login_required

# Create your views here.
# Article > views.py


def articles(request):
    keyword = request.GET.get("keyword")

    if keyword:
        all_articles = Article.objects.filter(title__contains=keyword)
        return render(request, "articles.html", {"articles": all_articles})

    all_articles = Article.objects.all()

    return render(request, "articles.html", {"articles": all_articles})


def index(request):
    context = {"message": "this is message from DJANGO",
               "number": 20,
               "numbers": [1, 2, 3, 4, 5, 6]}
    return render(request, "index.html", context)


def about(request):
    return render(request, "about.html")


def detail(request, id):
    return HttpResponse(f"Detail: {int(id)}")


@login_required(login_url="user:login")
def dashboard(request):

    article = Article.objects.filter(author=request.user)

    context = {
        "articles": article,
        "counter": 1
    }
    return render(request, "dashboard.html", context)


@login_required(login_url="user:login")
def add_article(request):
    if request.method == "POST":
        form = ArticleForm(request.POST, request.FILES or None)

        if form.is_valid():

            article = form.save(commit=False)
            article.author = request.user
            article.save()
            messages.success(request, "Successfully Added")
            return redirect("article:dashboard")
        else:
            return render(request, "add_article.html")

    else:
        form = ArticleForm()
        context = {
            "forms": form
        }
        return render(request, "add_article.html", context)


@login_required(login_url="user:login")
def ind_article(request, id):
    # indv_article = Article.objects.get(id=id)
    indv_article = get_object_or_404(Article, id=id)
    context = {
        "indv_article": indv_article
    }
    return render(request, "ind_article.html", context)


@login_required(login_url="user:login")
def ind_article_delete(request, id):
    article = get_object_or_404(Article, id=id)

    article.delete()

    messages.success(request, "Successfully deleted!")
    return redirect("article:dashboard")


@login_required(login_url="user:login")
def ind_article_edit(request, id):
    article = get_object_or_404(Article, id=id)

    form = ArticleForm(request.POST or None,
                       request.FILES or None, instance=article)
    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()

        messages.success(request, "Article Updated")
        return redirect("article:dashboard")
    return render(request, "update.html", {"forms": form})

    return render(request, "update.html")

templates/about.html
{% extends 'layout.html' %} {% block body %}

<div style="margin-top: 40px">
  <h3>About</h3>
  <hr />
  <p>
    Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ab ratione dicta
    porro sequi repudiandae quo magni inventore in, facilis tenetur dolorem odio
    deserunt ipsa magnam quae est repellendus voluptatum laborum incidunt
    molestias accusamus, laudantium temporibus provident vero? Mollitia, quia
    corporis.
  </p>
</div>

{% endblock body %}

templates/add_article.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}

{% block body %}

<div class="row">
  <div class="col-sm-9">
  {% if messages %}

  {% for message in messages %}
    <div class="alert alert-success" role="alert">
      {{ message }}
    </div>
  {% endfor %}  
  
{% endif %}
  
  <h3 class="mt-5"> ADD ARTICLE </h3>
    <hr/>
    <form method="POST" enctype="multipart/form-data"> 

        {% csrf_token %}
        {{ forms.media}}
        {{ forms|crispy }}
        <button type="submit" class="btn btn-primary">Submit</button>
        
    </form>
  
  </div>
</div>
    
{% endblock body %}

templates/article.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}

{% block body %}

<div class="row">
  <div class="col-sm-9">
  {% if messages %}

  {% for message in messages %}
    <div class="alert alert-success" role="alert">
      {{ message }}
    </div>
  {% endfor %}  
  
{% endif %}
  
  <h3 class="mt-5"> ADD ARTICLE </h3>
    <hr/>
    <form method="POST" enctype="multipart/form-data"> 

        {% csrf_token %}
        {{ forms.media}}
        {{ forms|crispy }}
        <button type="submit" class="btn btn-primary">Submit</button>
        
    </form>
  
  </div>
</div>
    
{% endblock body %}

templates/articles.html
{% extends 'layout.html' %} {% block body %}

<h1>ARTICLES BODDY</h1>

{% if articles %}

<div class="accordion">
  {% for article in articles %}
  <div class="card mt-4" style="border-bottom: 1px solid rgb(209, 209, 209)">
    <div class="card-header" id="headingOne">
      <h5 class="mb-0">
        <button
          class="btn btn-link"
          data-toggle="collapse"
          data-target="#collapseOne"
          aria-expanded="true"
          aria-controls="collapseOne"
        >
          {{article.title}}
        </button>
      </h5>
    </div>

    <div
      id="collapseOne"
      class="collapse show"
      aria-labelledby="headingOne"
      data-parent="#accordion"
    >
      <div class="card-body">
        <p class="lead">Author:{{article.author}}</p>
        {% if article.article_image %}
        <img
          class="img-fluid rounded"
          style="width: 150px"
          src="{{article.article_image.url}}"
          alt="{{image}}"
        />
        {% endif %}
        <hr />

        <p>{{ article.content|safe }}</p>
      </div>
    </div>
  </div>

  {% endfor %}
</div>
{% else %} No article currently appears {% endif %} {% endblock body %}

templates/dashboard.html
{% extends 'layout.html' %} {% block body %} {% if messages %}
<div class="alert alert-success" role="alert">{{ message }}</div>
{% endif %}

<h3 class="mt-4">Dashboard</h3>
<hr />
<p>Welcome to page <small>{{ request.user.username }}</small></p>

<a href="{% url 'article:article_add'%}" class="btn btn-success">Add Article</a>
<hr />

{% if articles %}
<table class="table">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Author</th>
      <th scope="col">Title</th>
      <th scope="col">Date</th>
    </tr>
  </thead>
  <tbody>
    {% for article in articles %}

    <tr>
      <th scope="row">{{ article.id }}</th>
      <td>{{article.author.username}}</td>
      <td><a href="{{article.id}}">{{article.title}}</a></td>
      <td>{{article.created_date|date:'N-d-Y | g:i:A'}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% else %}

<div class="alert alert-danger" role="alert">Please add article 👆</div>

{% endif %} {% endblock body %}

templates/ind_article.html
{% extends 'layout.html' %}

{% block body %}


<h3 class="mt-4">Article</h3>
<hr>
<p>Welcome to page <small>{{ request.user.username }}</small></p>


<div class="backdrop--sheet"></div>
  <div class="confirming--page">
      <p>Are you sure you want to delete?</p>
      
      <button class="btn btn-success" id="cancel-me">Cancel</button>
      <a href="delete/{{indv_article.id}}"><button class="btn btn-danger">
          Delete
      </button>
      </a>
  </div>
  
<div class="jumbotron indv--item">
  
  {% if indv_article.article_image %}
  <img class="img-fluid rounded" style="width:150px"src="{{indv_article.article_image.url}}" alt="{{image}}">
  <hr>
  {% endif %}
  
  <div class="indv--item__action" id="indv--item__action"> 
      
      {% comment %} href="edit/{{indv_article.id}}" {% endcomment %}
      
      <a class="indv--item__action-item" href="edit/{{indv_article.id}}"> 
        <i class="far fa-edit"></i>
      </a>  
      <a  class="indv--item__action-item" id="delete_me"> 
        <i class="far fa-trash-alt focus"></i>
      </a>  
  </div>
  
  
 
  
  <h4 class="display-4">{{indv_article.title}}</h4>
  <p class="lead">{{indv_article.author}}</p>
  <hr class="my-4">
  <p>{{ indv_article.content|safe }}</p>
 
  
</div>



{% endblock body %}

templates/index.html
{% extends 'layout.html' %} {% block body %}

{% if messages %}

  {% for message in messages %}
    <div class="alert alert-success" role="alert">
      {{ message }}
    </div>
  {% endfor %}  
  
{% endif %}
     
<div class="jumbotron text-center" style="margin-top: 20px">
  <h3>Software Blog</h3>
  <p>This is our first software blog and we are excited to move forward!</p>
</div>


{% endblock body %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>YBBlog</title>
    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.15.2/css/all.css"
      integrity="sha384-vSIIfh2YWi9wW0r9iZe7RJPrKwp6bG+s9QZMoITbCckVJqGCCRhc+ccxNcdpHuYu"
      crossorigin="anonymous"
    />

    <link rel="stylesheet" href="{% static 'ind_article.css'%}" />
    <link rel="stylesheet" href="{% static 'css/style.css'%}" />
  </head>
  <body>
    {% include "includes/navbar.html" %}
    <div class="container mt-1">{% block body %} {% endblock body %}</div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"
    ></script>
    <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>
    <script src="{% static 'js/script.js'%}"></script>
  </body>
</html>

templates/login.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}

{% block body %}

<div class="row">
  <div class="col-md-6 offset-md-3">
  {% if messages %}

  {% for message in messages %}
    <div class="alert alert-success" role="alert">
      {{ message }}
    </div>
  {% endfor %}  
  
{% endif %}
  
  <h3 class="mt-5"> USER LOGIN </h3>
    <hr/>
    <form method="POST"> 

        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Submit</button>
        
    </form>
  
  </div>
</div>
    
{% endblock body %}

templates/register.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}

{% block body  %}

<div class="row">
  <div class="col-md-6 offset-md-3">
  <h3 class="mt-5"> USER REGISTRATION </h3>
  <hr>
  <form method="POST" class="mt-5">
    {% csrf_token %}

    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
  </div>
</div>




{% endblock body %}

templates/update.html
{% extends 'layout.html' %} {% load crispy_forms_tags %} {% block body %}

<div class="row">
  <div class="col-sm-9">
    {% if messages %} {% for message in messages %}
    <div class="alert alert-success" role="alert">{{ message }}</div>
    {% endfor %} {% endif %}

    <h3 class="mt-5">Update Article</h3>
    <hr />
    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %} {{ forms.media}} {{ forms|crispy }}
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
  </div>
</div>

{% endblock body %}